# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.7'
        check-latest: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Verify Go version
      run: go version

  e2e-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.7'
        check-latest: false

    - name: Make e2e test script executable
      run: chmod +x scripts/e2e_test.sh
  
    - name: Run E2E Test
      run: ./scripts/e2e_test.sh
